#!/bin/bash
#
# FileName: fix-my-terminal.sh
# Description: A portable and interactive script to fix common terminal issues like
#              unresponsive keys (Home, End, etc.) and garbled text when pasting.
#              It detects the user's shell (Bash/Zsh) and applies fixes safely.
#

# --- Configuration for .inputrc ---
# This block contains the ideal settings we want to ensure are in .inputrc
read -r -d '' INPUTRC_CONFIG <<'EOF'
# Generated by fix-my-terminal.sh to improve key bindings and paste behavior

# Fix Home and End keys
"\e[H": beginning-of-line
"\e[F": end-of-line
"\e[1~": beginning-of-line
"\e[4~": end-of-line
"\e[7~": beginning-of-line
"\e[8~": end-of-line
"\eOH": beginning-of-line
"\eOF": end-of-line

# Fix PageUp and PageDown for history search
"\e[5~": history-search-backward
"\e[6~": history-search-forward

set enable-bracketed-paste on
EOF

# --- Helper Functions ---
print_message() {
    local color=$1
    local message=$2
    case $color in
        "green") echo -e "\n\e[32m✅ ${message}\e[0m" ;;
        "red") echo -e "\n\e[31m❌ ${message}\e[0m" ;;
        "blue") echo -e "\n\e[34mℹ️  ${message}\e[0m" ;;
        "yellow") echo -e "\n\e[33m⚠️  ${message}\e[0m" ;;
    esac
}

ask_for_confirmation() {
    read -p "   Möchten Sie diese Änderung anwenden? (j/N): " choice
    if [[ "$choice" =~ ^[jJ](a|A)?$ ]]; then
        return 0 # Success (yes)
    else
        return 1 # Failure (no)
    fi
}

# --- Main Logic Functions ---

# 1. Fix the TERM environment variable
fix_term_variable() {
    print_message "blue" "Schritt 1: Überprüfung der TERM-Umgebungsvariable..."
    
    local shell_config_file=""
    # Detect shell configuration file
    if [[ "$SHELL" == *"zsh"* ]]; then
        shell_config_file="$HOME/.zshrc"
    elif [[ "$SHELL" == *"bash"* ]]; then
        shell_config_file="$HOME/.bashrc"
    else
        print_message "yellow" "Unbekannte Shell ($SHELL) erkannt. TERM-Variable kann nicht automatisch gesetzt werden."
        return
    fi

    # Check if TERM needs to be set
    if ! grep -q "export TERM=xterm-256color" "$shell_config_file"; then
        echo "   Ihre TERM-Variable ist möglicherweise nicht optimal eingestellt."
        echo "   Es wird empfohlen, 'export TERM=xterm-256color' zu Ihrer Konfigurationsdatei hinzuzufügen."
        
        if ask_for_confirmation; then
            echo -e "\n# Set terminal type for proper key support\nexport TERM=xterm-256color" >> "$shell_config_file"
            print_message "green" "'export TERM=xterm-256color' wurde zu $shell_config_file hinzugefügt."
        else
            print_message "yellow" "Schritt übersprungen."
        fi
    else
        print_message "green" "Die TERM-Variable ist bereits korrekt in $shell_config_file konfiguriert."
    fi
}

# 2. Fix the .inputrc file
fix_inputrc_file() {
    print_message "blue" "Schritt 2: Überprüfung der Tastenbelegungs-Datei (~/.inputrc)..."
    local inputrc_file="$HOME/.inputrc"

    if [ ! -f "$inputrc_file" ]; then
        echo "   Die Datei ~/.inputrc existiert nicht."
        echo "   Diese Datei ist entscheidend für die korrekte Funktion von Tasten wie Pos1/Ende und für fehlerfreies Einfügen."
        
        if ask_for_confirmation; then
            echo "$INPUTRC_CONFIG" > "$inputrc_file"
            print_message "green" "Die Datei ~/.inputrc wurde mit den empfohlenen Einstellungen erstellt."
        else
            print_message "yellow" "Schritt übersprungen."
        fi
    else
        # File exists, check for missing content
        local missing_config=""
        # Use a simple line-by-line check to find what's missing
        while IFS= read -r line; do
            # Skip comments and empty lines for the check
            if [[ ! "$line" =~ ^# && -n "$line" ]]; then
                if ! grep -Fxq "$line" "$inputrc_file"; then
                    missing_config+="$line\n"
                fi
            fi
        done <<< "$INPUTRC_CONFIG"
        
        if [ -n "$missing_config" ]; then
            echo "   Ihre ~/.inputrc ist vorhanden, aber einige empfohlene Einstellungen für Tastenbelegung und Einfügen fehlen."
            
            if ask_for_confirmation; then
                # Add a separator and then the missing lines
                echo -e "\n# Added by fix-my-terminal.sh" >> "$inputrc_file"
                echo -e "$missing_config" >> "$inputrc_file"
                print_message "green" "Die fehlenden Einstellungen wurden zu ~/.inputrc hinzugefügt."
            else
                print_message "yellow" "Schritt übersprungen."
            fi
        else
            print_message "green" "Ihre ~/.inputrc-Datei enthält bereits alle empfohlenen Einstellungen."
        fi
    fi
}

# --- Main Script ---
main() {
    clear
    echo "================================================="
    echo "       Terminal-Problemlöser by PS-Coding        "
    echo "================================================="
    echo
    echo "Dieses Skript hilft Ihnen, häufige Terminal-Probleme zu beheben,"
    echo "indem es Ihre Shell-Konfiguration überprüft und korrigiert."
    echo "Es werden keine Änderungen ohne Ihre Zustimmung vorgenommen."
    echo

    fix_term_variable
    fix_inputrc_file
    
    print_message "green" "======================================================================="
    print_message "green" "Die Überprüfung ist abgeschlossen."
    print_message "green" "Damit alle Änderungen wirksam werden, starten Sie bitte eine neue"
    print_message "green" "Terminal-Sitzung oder laden Sie Ihre Konfiguration neu mit:"
    if [[ "$SHELL" == *"zsh"* ]]; then
        echo "   source ~/.zshrc"
    else
        echo "   source ~/.bashrc"
    fi
    print_message "green" "======================================================================="
    
    print_message "blue" "Das Skript bleibt aktiv. Drücken Sie eine beliebige Taste zum Beenden."
    read -n 1 -s -r
}

# --- Run Script ---
main
